### ISSUE TITLE
Takumi Todo

### ISSUE THREAD

**Issue by takumihara** [usatie/pong#66]
Review1回後

- [x] 横向きにする : #274 
- [x] 招待機能あるから、もしかしたらルーム名指定して参加っていう機能いらないかもね。UIがごちゃごちゃする : #275 
- [x] dark modeの時のボールの色 : #277
- [x] create a new roomした時にviewerになる : #276
- [x] 誰が対戦してるのか見たい : #280
- [ ] 画面が広い時に点数表示が微妙になる
- [x] 相手が抜けた時の対応 : https://github.com/usatie/pong/pull/298
- [ ] Replay機能やりたい！！！
- [ ] ゲーム性を足す
  - パドルの一部にスピードアップ範囲を作って、そこに当てたら一時的にボールが加速する
  - ボールが増える
- [x] viewer途中から参加？ 
- [x] 再参加したときに点数がリセット : https://github.com/usatie/pong/pull/298

Backlog
- [ ] bounce_off_paddle ?
- [ ] `OAuth2 in Action` 読む（+usamiさんに質問する）
- [ ] practice mode周りの細かい設定
- [ ] 別のマップ
- [ ] `it must be faithful to the original Pong (1972).`
- [ ] desginをもっとレトロな感じに
- [ ] socketのemitが失敗した時？（code rabbit）
- [ ] 観戦開始時にゲームがすでに始まってた時のハンドル
- [ ] だれが戦っているのかをゲーム画面に出す

must

- [ ] 横向きに直す
- [ ] customization

Pong Feature Backlog
- チーム戦
- パドルの角度を変えられるように
- パドルの速度でボールを加速
- パドルを前に動かせる

week 12/27~
- [x] 現在、戦ってる途中のゲーム一覧を表示
- [ ] 話す: https://github.com/usatie/pong/pull/164/
- [x] ログイン状態に応じて、フロントエンドの変更
- [x] viewer側のログの整理
- [ ] リプレイ機能
- [ ] （ゲーム途中で）人が抜けた時のハンドル

week 12/20~
- [x] websocket race condition解決: https://github.com/usatie/pong/pull/172
- [x] ~ServerComponentのRFC読む：https://github.com/reactjs/rfcs/blob/main/text/0188-server-components.md~
- [x] React Hooksの勉強: [Introducing Hooks – React](https://legacy.reactjs.org/docs/hooks-intro.html)
- [x] game終了時、history作成
- [ ] 話す: https://github.com/usatie/pong/pull/164/
- [x] add auth to websocket

week 12/13-
- [x] 観戦機能 : #146 
- [x] #136
- [x] gameとreactのdecoupling: https://github.com/usatie/pong/pull/148
- [x] server componentの動画見る
- [x] refac: game logicからsocketをなくす。 onRightとかのハンドラーを渡すようにする

week 12/6-
- [x] 2回目以降startボタンを押さなくても始まるように : #130
- [x] review #111 
- [x]  勝敗判定 : #130
- [x] JSのasynchronous勉強する : [非同期JS](https://takumihara.notion.site/JS-86aed315c48e419eb2f7d5c852ac7b91)(https://zenn.dev/estra/books/js-async-promise-chain-event-loop)
- [ ] replayのSPEC作成 : #129 
- [x] transactionについて調べる（ #122 ）

week 11/29-
- [x] game: PongGame | undefinedにしてuseState使う : #108 
- [x] startの引数の型 : #109
- [x] マッチメイキング : #110

Week 11/22-

- [ ] 本読み終えて大事なところまとめる（11/15から繰越）
- [x] stop sending `roomId`  <- #78 
- [x] `useEffect` の正しい使い方調べる。分けて使うのか？: #84
- [x] socket.ioで複数moduleがあったら : #83 
- [x] #76 
- [x] 既にPaddleをうごかしてたときのhandle
- [x] `start`ボタン
- [x] canvasからの情報を描画（追加）: #81
- [x] socketの持ち方をリファクタ（追加） : #84
- [x] 接続の状況のロギングの機能（追加）: #86
- [x] 接続数が多すぎた時のhandle（追加）: #86
- [x] socket ioからリクエストが6個くらいいく（追加）: #88

Week 11/15-

- [ ] 本読み終えて大事なところまとめる <- 具体的な実装以外読んだけどまとめられてないので、来週にもちこし
- [x] vanilla JS -> React 
- [x] pongの部屋を分けて、複数グループが同時に対戦できるようにする <- #63 
- [x] 衝突判定を通信する <- #65
- [x] 非同期な描画を試す <- #65

11/20反省
- ボールがたまに消える
- 相手に当たった時にのめり込んで見える
- startボタン何回も押せるのが地味に面白い（回数制限して機能にしてもよいかも）
